name = New
description = A simple custom layout.
preview = preview.png
template = new-layout

; Regions
<!--regions[branding]       = Branding-->
<!--regions[header]         = Header-->
<!--regions[navigation]     = Navigation bar-->
<!--regions[highlighted]    = Highlighted-->
<!--regions[help]           = Help-->
regions[content]        = Content
<!--regions[sidebar_first]  = First sidebar-->
<!--regions[sidebar_second] = Second sidebar-->
<!--regions[footer]         = Footer-->

; Stylesheets
stylesheets[all][] = css/layouts/new/new.layout.css
