<?php

/**
 * Implements hook_permission().
 *
 * Provides a demonstration access string.
 */
function custom_menu_permission() {

  return [
    'custom menu select user' => array('title' => t('Access the protected select user'),),
    'custom menu edit user' => array('title' => t('Access the protected edit user'),),
    'custom menu delete user' => array('title' => t('Access the protected delete user'),),
    'custom menu damp SQL' => array('title' => t('Access the protected damp SQL'),),
    'custom menu run CRON' => array('title' => t('Access the protected run CRON'),),
  ];
}

/**
 * Implements hook_menu().
 */
function custom_menu_menu() {

  $items['admin/menu_custom'] = array(
    'title' => 'Menu DZ',
    'description' => 'Simplest possible menu type, and the parent menu entry for others',
    'page callback' => 'custom_menu_page_callback',
    'weight' => '10',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/system'] = array(
    'title' => 'System',
    'description' => 'System menu',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_system_page_callback',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/profile'] = array(
    'title' => 'Profile',
    'description' => 'Profile menu',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_profile_page_callback',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/profile/show'] = array(
    'title' => 'Show profile',
    'description' => 'Show my profile',
    'page callback' => 'custom_menu_profile_page_callback',
    'access callback' => 'user_is_logged_in',
    'expanded' => TRUE,
    'weight' => '1',
  );

  $items['admin/menu_custom/profile/edit'] = array(
    'title' => 'Edit profile',
    'description' => 'Edit my profile',
    'page callback' => 'custom_menu_profile_page_callback',
    'access callback' => 'user_is_logged_in',
    'expanded' => TRUE,
    'weight' => '2',
  );

  $items['admin/menu_custom/profile/select_user'] = array(
    'title' => 'Administration profiles',
    'description' => 'Administration users profiles',
    'page callback' => 'custom_menu_profile_page_callback',
    'access arguments' => ['custom menu select user'],
    'expanded' => TRUE,
    'weight' => '3',
  );

  $items['admin/menu_custom/profile/select_user/edit'] = array(
    'title' => 'Edit profile',
    'description' => 'Edit user profile',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_profile_page_callback',
    'access arguments' => ['custom menu edit user'],
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/profile/select_user/delete'] = array(
    'title' => 'Delete profile',
    'description' => 'Delete user profile',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_profile_page_callback',
    'access arguments' => ['custom menu delete user'],
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/system/cc'] = array(
    'title' => 'Clear cache',
    'description' => 'Clear cache ',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_system_cc_page_callback',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/system/dampDB'] = array(
    'title' => 'Damp DB',
    'description' => 'Damp MySQL database',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_system_page_callback',
    'access arguments' => ['custom menu damp SQL'],
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/system/runCRON'] = array(
    'title' => 'Run CRON',
    'description' => 'Run CRON action',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_system_page_callback',
    'access arguments' => ['custom menu run CRON'],
    'expanded' => TRUE,
  );

  $items['get_node/%/show'] = array(

    'title callback' => 'node_page_title_from_nid',
    'title' => 'Show title',
    'title arguments' => [1],
    'page callback' => 'custom_menu_node_page_callback',
    'page arguments' => [1],
    'type' => MENU_LOCAL_TASK,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 *
 * @param $items
 */
function custom_menu_menu_alter(&$items) {
  $items['admin/dashboard']['title'] = 'Panel';
  $items['admin/content']['title'] = 'Filling';
  $items['admin/structure']['title'] = 'Architecture';
  $items['admin/appearance']['title'] = 'Themes';
  $items['admin/people']['title'] = 'Users';
  $items['admin/modules']['title'] = 'Mod';
  $items['admin/config']['title'] = 'Conf';
  $items['admin/reports']['title'] = 'Return';
  $items['admin/help']['title'] = 'Support';
  $items['admin/menu_custom']['title'] = 'Custom';

  foreach ($items as $route => $item) {
    $result = module_invoke_all('custom_menu_menu', $route);
    drupal_alter('custom_menu_menu', $result, $route);
    foreach ($result as $subroute => $subitem) {
      $items[$route . '/' . $subroute] = $subitem;
    }
  }
}

/**
 * Implements hook_custom_menu_menu().
 *
 * @param $route
 *
 * @return array
 */
function custom_menu_custom_menu_menu($route) {
  $subitems = [];
  if ($route == 'admin/menu_custom') {
    $subitems['help'] = array(
      'title' => 'Help',
      'description' => 'Simplest possible menu type, and the parent menu entry for others',
      'weight' => '3',
      'access callback' => TRUE,
      'expanded' => TRUE,
      'page callback' => 'custom_menu_help_page_callback',
    );
  }
  return $subitems;
}

/**
 * Page callback.
 * admin/menu_custom
 */
function custom_menu_page_callback() {

  return ('Under development..');
}

/**
 * Page callback.
 * admin/menu_custom/system
 * admin/menu_custom/system/dampDB
 * admin/menu_custom/system/runCRON
 */
function custom_menu_system_page_callback() {

  return t('Successful:)');
}

/**
 * Page callback.
 * admin/menu_custom/system/cc
 */
function custom_menu_system_cc_page_callback() {

  return t('Cache was cleared..');
}

/**
 * Page callback.
 * admin/menu_custom/profile
 * admin/menu_custom/profile/show
 * admin/menu_custom/profile/edit
 * admin/menu_custom/profile/select_user
 * admin/menu_custom/profile/select_user/edit
 * admin/menu_custom/profile/select_user/delete
 *
 */
function custom_menu_profile_page_callback() {

  return t('Hello!');
}

/**
 * Page callback.
 * /get_node/%7
 *
 * @param $nid
 *
 * @return
 */
function custom_menu_node_page_callback($nid) {
  $node = node_load($nid);

  return $node->title;
}

/**
 * Page callback.
 * /admin/menu_custom/help
 *
 * @return null|string
 */
function custom_menu_help_page_callback() {

  return t('Help page');
}
