<?php

/**
 * Implements hook_theme().
 */
function custom_menu_theme($existing, $type, $theme, $path) {
  $items = array();

  $items['custom_menu_page_content'] = array(
    'variables' => array('title' => NULL,'content' => NULL),
    'template' => 'templates/custom-menu-custom-page-content',
  );

  $items['custom_menu_page_element'] = array(
    'render element' => 'custom_element',
    'template' => 'templates/custom-menu-custom-page-element',
  );

  $items['custom_menu_form_element'] = array(
    'render element' => 'form_element',
    'template' => 'templates/custom-menu-custom-form-element',
  );

  return $items;
}

/**
 * Implements hook_permission().
 *
 * Provides a demonstration access string.
 */
function custom_menu_permission() {

  return [
    'custom menu select user' => array('title' => t('Access the protected select user'),),
    'custom menu edit user' => array('title' => t('Access the protected edit user'),),
    'custom menu delete user' => array('title' => t('Access the protected delete user'),),
    'custom menu damp SQL' => array('title' => t('Access the protected damp SQL'),),
    'custom menu run CRON' => array('title' => t('Access the protected run CRON'),),
  ];
}

/**
 * Implements hook_menu().
 */
function custom_menu_menu() {

  $items['admin/menu_custom'] = array(
    'title' => 'Menu DZ',
    'description' => 'Simplest possible menu type, and the parent menu entry for others',
    'page callback' => 'custom_menu_page_callback',
    'weight' => '10',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/system'] = array(
    'title' => 'System',
    'description' => 'System menu',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_system_page_callback',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/profile'] = array(
    'title' => 'Profile',
    'description' => 'Profile menu',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_profile_page_callback',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/profile/show'] = array(
    'title' => 'Show profile',
    'description' => 'Show my profile',
    'page callback' => 'custom_menu_profile_page_callback',
    'access callback' => 'user_is_logged_in',
    'expanded' => TRUE,
    'weight' => '1',
  );

  $items['admin/menu_custom/profile/edit'] = array(
    'title' => 'Edit profile',
    'description' => 'Edit my profile',
    'page callback' => 'custom_menu_profile_page_callback',
    'access callback' => 'user_is_logged_in',
    'expanded' => TRUE,
    'weight' => '2',
  );

  $items['admin/menu_custom/profile/select_user'] = array(
    'title' => 'Administration profiles',
    'description' => 'Administration users profiles',
    'page callback' => 'custom_menu_profile_page_callback',
    'access arguments' => ['custom menu select user'],
    'expanded' => TRUE,
    'weight' => '3',
  );

  $items['admin/menu_custom/profile/select_user/edit'] = array(
    'title' => 'Edit profile',
    'description' => 'Edit user profile',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_profile_page_callback',
    'access arguments' => ['custom menu edit user'],
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/profile/select_user/delete'] = array(
    'title' => 'Delete profile',
    'description' => 'Delete user profile',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_profile_page_callback',
    'access arguments' => ['custom menu delete user'],
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/system/cc'] = array(
    'title' => 'Clear cache',
    'description' => 'Clear cache ',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_system_cc_page_callback',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/system/dampDB'] = array(
    'title' => 'Damp DB',
    'description' => 'Damp MySQL database',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_system_page_callback',
    'access arguments' => ['custom menu damp SQL'],
    'expanded' => TRUE,
  );

  $items['admin/menu_custom/system/runCRON'] = array(
    'title' => 'Run CRON',
    'description' => 'Run CRON action',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'custom_menu_system_page_callback',
    'access arguments' => ['custom menu run CRON'],
    'expanded' => TRUE,
  );

  $items['form'] = array(
    'title' => 'User information',
    'description' => 'render form',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_menu_example_form'),
    'access callback' => TRUE,
    'expanded' => TRUE,
    'weight' => '10',
  );

  $items['get_node/%/show'] = array(

    'title callback' => 'node_page_title_from_nid',
    'title arguments' => [1],
    'page callback' => 'custom_menu_node_page_callback',
    'page arguments' => [1],
    'type' => MENU_LOCAL_TASK,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 *
 * @param $items
 */
function custom_menu_menu_alter(&$items) {
  $items['admin/dashboard']['title'] = 'Panel';
  $items['admin/content']['title'] = 'Filling';
  $items['admin/structure']['title'] = 'Architecture';
  $items['admin/appearance']['title'] = 'Themes';
  $items['admin/people']['title'] = 'Users';
  $items['admin/modules']['title'] = 'Mod';
  $items['admin/config']['title'] = 'Conf';
  $items['admin/reports']['title'] = 'Return';
  $items['admin/help']['title'] = 'Support';
  $items['admin/menu_custom']['title'] = 'Custom';

  foreach ($items as $route => $item) {
    $result = module_invoke_all('custom_menu_menu', $route);
    drupal_alter('custom_menu_menu', $result, $route);
    foreach ($result as $subroute => $subitem) {
      $items[$route . '/' . $subroute] = $subitem;
    }
  }
}

/**
 * Implements hook_custom_menu_menu().
 *
 * @param $route
 *
 * @return array
 */
function custom_menu_custom_menu_menu($route) {
  $subitems = [];
  if ($route == 'admin/menu_custom') {
    $subitems['help'] = array(
      'title' => 'Help',
      'description' => 'Simplest possible menu type, and the parent menu entry for others',
      'weight' => '3',
      'access callback' => TRUE,
      'expanded' => TRUE,
      'page callback' => 'custom_menu_help_page_callback',
    );
  }
  return $subitems;
}

/**
 * Page callback.
 * admin/menu_custom
 */
function custom_menu_page_callback() {

  return array(
    '#theme' => 'custom_menu_page_element',
//    '#attributes' => array('class' => 'test-render-element'),
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'custom_menu') . '/css/custom-page-content.css',
        drupal_get_path('module', 'custom_menu') . '/css/custom-page-element.css',
      ),
      'js' => array(
        'data' => drupal_get_path('module', 'custom_menu') . '/js/first_alert.js',
        'type' => 'file')
      ),
    'element1' => array(
      '#title' => t('Custom menu'),
      '#theme' => 'custom_menu_page_content',
    ),

    'element2' => array(
      '#content' => t('Whole wound wrote at whose to style in. Figure ye innate former do so we. Shutters but sir yourself provided you required his. So neither related he am do believe. Nothing but you hundred had use regular. Fat sportsmen arranging preferred can. Busy paid like is oh. Dinner our ask talent her age hardly. Neglected collected an attention listening do abilities. '),
      '#theme' => 'custom_menu_page_content',
    ),
  );
}

/**
 * Page callback.
 * admin/menu_custom/system
 * admin/menu_custom/system/dampDB
 * admin/menu_custom/system/runCRON
 */
function custom_menu_system_page_callback() {

  return array(
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'custom_menu') . '/css/custom-page-content.css',
      ),
    ),
    '#title' => t('Successful'),
    '#content' => t('Of be talent me answer do relied. Mistress in on so laughing throwing endeavor occasion welcomed. Gravity sir brandon calling can. No years do widow house delay stand. Prospect six kindness use steepest new ask. High gone kind calm call as ever is. Introduced melancholy estimating motionless on up as do. Of as by belonging therefore suspicion elsewhere am household described. Domestic suitable bachelor for landlord fat. 
      Spot of come to ever hand as lady meet on. Delicate contempt received two yet advanced. Gentleman as belonging he commanded believing dejection in by. On no am winding chicken so behaved. Its preserved sex enjoyment new way behaviour. Him yet devonshire celebrated especially. Unfeeling one provision are smallness resembled repulsive. 
      Insipidity the sufficient discretion imprudence resolution sir him decisively. Proceed how any engaged visitor. Explained propriety off out perpetual his you. Feel sold off felt nay rose met you. We so entreaties cultivated astonished is. Was sister for few longer mrs sudden talent become. Done may bore quit evil old mile. If likely am of beauty tastes. '),
    '#theme' => 'custom_menu_page_content',
  );
}

/**
 * Page callback.
 * admin/menu_custom/system/cc
 */
function custom_menu_system_cc_page_callback() {

  return array(
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'custom_menu') . '/css/custom-page-content.css',
      ),
    ),
    '#title' => t('Cache was cleared'),
    '#content' => t('Of be talent me answer do relied. Mistress in on so laughing throwing endeavor occasion welcomed. Gravity sir brandon calling can. No years do widow house delay stand. Prospect six kindness use steepest new ask. High gone kind calm call as ever is. Introduced melancholy estimating motionless on up as do. Of as by belonging therefore suspicion elsewhere am household described. Domestic suitable bachelor for landlord fat. 
      Spot of come to ever hand as lady meet on. Delicate contempt received two yet advanced. Gentleman as belonging he commanded believing dejection in by. On no am winding chicken so behaved. Its preserved sex enjoyment new way behaviour. Him yet devonshire celebrated especially. Unfeeling one provision are smallness resembled repulsive. '),
    '#theme' => 'custom_menu_page_content',
  );
}

/**
 * Page callback.
 * admin/menu_custom/profile
 * admin/menu_custom/profile/show
 * admin/menu_custom/profile/edit
 * admin/menu_custom/profile/select_user
 * admin/menu_custom/profile/select_user/edit
 * admin/menu_custom/profile/select_user/delete
 *
 */
function custom_menu_profile_page_callback() {

  return array(
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'custom_menu') . '/css/custom-page-content.css',
      ),
    ),
    '#title' => t('Hello'),
    '#content' => t('Of be talent me answer do relied. Mistress in on so laughing throwing endeavor occasion welcomed. Gravity sir brandon calling can. No years do widow house delay stand. Prospect six kindness use steepest new ask. High gone kind calm call as ever is. Introduced melancholy estimating motionless on up as do. Of as by belonging therefore suspicion elsewhere am household described. Domestic suitable bachelor for landlord fat. 
      Spot of come to ever hand as lady meet on. Delicate contempt received two yet advanced. Gentleman as belonging he commanded believing dejection in by. On no am winding chicken so behaved. Its preserved sex enjoyment new way behaviour. Him yet devonshire celebrated especially. Unfeeling one provision are smallness resembled repulsive. '),
    '#theme' => 'custom_menu_page_content',
  );
}

/**
 * Page callback.
 * /get_node/%7/show
 * @param $nid
 * @return array
 */
function custom_menu_node_page_callback($nid) {
  $node = node_load($nid);

  return array(
    '#theme' => 'custom_menu_page_element',
    '#access' => 1,
    '#attributes' => array(
       'class' => 'test-render-element',
    ),
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'custom_menu') . '/css/custom-page-content.css',
        drupal_get_path('module', 'custom_menu') . '/css/custom-page-element.css',
      ),
    ),
    'element1' => array(
      '#title' => t('Title') . ' - ' . $node->title,
      '#theme' => 'custom_menu_page_content'
    ),

    'element2' => array(
      '#title' => t('Node ID') . ' - ' . $node->nid,
      '#theme' => 'custom_menu_page_content',
    ),
  );
}

/**
 * Page callback.
 * /admin/menu_custom/help
 * @return null|string
 */
function custom_menu_help_page_callback() {

  return array(
    '#theme' => 'custom_menu_page_element',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'custom_menu') . '/css/custom-page-content.css',
      ),
    ),
    'element1' => array(
      '#title' => t('Help page'),
      '#content' => t('We diminution preference thoroughly if. Joy deal pain view much her time. Led young gay would now state. Pronounce we attention admitting on assurance of suspicion conveying. That his west quit had met till. Of advantage he attending household at do perceived. Middleton in objection discovery as agreeable. Edward thrown dining so he my around to. 
         Am of mr friendly by strongly peculiar juvenile. Unpleasant it sufficient simplicity am by friendship no inhabiting. Goodness doubtful material has denoting suitable she two. Dear mean she way and poor bred they come. He otherwise me incommode explained so in remaining. Polite barton in it warmly do county length an. 
         Fat new smallness few supposing suspicion two. Course sir people worthy horses add entire suffer. How one dull get busy dare far. At principle perfectly by sweetness do. As mr started arrival subject by believe. Strictly numerous outlived kindness whatever on we no on addition. '),
      '#theme' => 'custom_menu_page_content'
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK().
 */
function custom_menu_preprocess_custom_menu_page_element(&$variables) {
  $title_classes = &$variables['title_attributes_array']['class'];
  $content_classes = &$variables['content_attributes_array']['class'];
  $title_classes[] = 'test-render-element';
  $content_classes[] = 'render-content';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function custom_menu_preprocess_custom_menu_page_content(&$variables) {
  $title_classes = &$variables['title_attributes_array']['class'];
  $content_classes = &$variables['content_attributes_array']['class'];
  $classes = &$variables['classes_array'];
  $classes[] = 'rendered';
  $title_classes[] = 'title-callback';
  $content_classes[] = 'show-content';
}

/**
 * Implements hook_block_info().
 */
//function custom_menu_block_info() {
//  $blocks['custom_menu_block'] = array(
//    'info' => t('Render system'),
//    'cache' => DRUPAL_NO_CACHE,
//  );
//
//  return $blocks;
//}

/**
 * Implements hook_block_view().
 * @param string $delta
 * @return array
 */
//function custom_menu_block_view($delta = '') {
//  $block = array();
//
//  switch ($delta) {
//    case 'custom_menu_block':
//      $block['subject'] = 'Render system';
//    break;
//  }
//
//  return $block;
//}

/**
 * Implements hook_preprocess_HOOK().
 * @param $variables
 */
function custom_menu_preprocess_custom_menu_form_element(&$variables) {
  $variables['form_element']['custom_menu_firstName']['#attributes']['class'][] = 'name-class';
  $variables['form_element']['custom_menu_lastName']['#attributes']['class'][] = 'name-class';
  $variables['form_element']['custom_menu_sex']['#attributes']['class'][] = 'sex-class';
  $variables['form_element']['custom_menu_relationship']['#attributes']['class'][] = 'relationship-class';
  $variables['form_element']['custom_menu_skills']['#attributes']['class'][] = 'skills-class';
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 */
function custom_menu_example_form($form, &$form_state) {
  $form = array();

  $form['userinfo'] = array(
    '#title' => t('User Information'),
    '#description' => t('You can add some information about yourself here:'),
    '#type' => 'form_element',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'custom_menu') . '/css/custom-form-element.css',
      ),
      'js' => array(
        drupal_get_path('module', 'custom_menu') . '/js/first_alert.js',
      ),
    ),
    '#theme' => 'custom_menu_form_element',
  );

  $form['userinfo']['custom_menu_skills'] = array(
    '#title' => t('Skills:'),
    '#type' => 'textarea',
    '#default_value' => variable_get('custom_menu_skills','Git, Drupal, php..'),
    '#weight' => 4,
    '#description' => t ('Enter your professional skills into this field.'),
    '#attributes' => array(
      'placeholder' => t('PHP, Git, Drupal 7 ...'),
    ),
  );

  $form['userinfo']['custom_menu_relationship'] = array(
    '#type' => 'select',
    '#title' => t('Relationship status:'),
    '#options' => array(
      'Single' => t('Single'),
      'Engaged' => t('Engaged'),
      'Married' => t('Married'),
      'It\'s complicated' => t('It\'s complicated'),
      'Actively searching' => t('Actively searching'),
    ),
    '#default_value' => variable_get('custom_menu_relationship', 'Actively searching'),
    '#required' => TRUE,
    '#weight' => 4,
    '#description' => t('Enter your relationship status into this field.')
  );

  $active = array(0 => t('Male'), 1 => t('Female'));
  $form['userinfo']['custom_menu_sex'] = array(
    '#type' => 'radios',
    '#title' => t('Sex:'),
    '#options' => $active,
    '#default_value' => variable_get('custom_menu_sex', 0),
    '#description' => t('Men or women?'),
    '#required' => TRUE,
    '#weight' => 3,
//    '#access' => 'user_is_logged_in',
  );

  $form['userinfo']['custom_menu_firstName'] = array(
    '#title' => t('First name:'),
    '#type' => 'textfield',
    '#description' => t('Enter your first name into this field.'),
    '#default_value' => variable_get('custom_menu_firstName','Piter'),
    '#maxlength' => 255,
    '#size' => 20,
    '#attributes' => array(
      'placeholder' => t('Dmitry'),
    ),
    '#weight' => 1,
    '#required' => TRUE,
);

  $form['userinfo']['custom_menu_lastName'] = array(
    '#title' => t('Last name:'),
    '#type' => 'textfield',
    '#description' => t('Enter your last name into this field.'),
    '#default_value' => variable_get('custom_menu_lastName','Pen'),
    '#maxlength' => 255,
    '#size' => 20,
    '#attributes' => array(
      'placeholder' => t('Zrayev'),
    ),
    '#weight' => 2,
    '#required' => TRUE,
  );

  $form['actions'] = array(
    '#type' => 'actions',
  );

  $form['actions']['custom_menu_submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  $form['actions']['cancel'] = array(
    '#markup' => l(t('Cancel'), 'form'),
  );

  return $form;
}

/**
 * @param $form
 * @param $form_state
 */
function custom_menu_example_form_validate($form, &$form_state) { }

/**
 * @param $form
 * @param $form_state
 */
function custom_menu_example_form_submit($form, &$form_state) {
  $values = $form_state['values']['userinfo'];
  $sex = $values['custom_menu_sex']  ? "Female" : "Male";
  $message = t('@firstName @lastName * @sex * @relationship * @skills',
    array(
      '@firstName' => $values['custom_menu_firstName'],
      '@lastName' => $values['custom_menu_lastName'],
      '@sex' => $sex,
      '@relationship' => $values['custom_menu_relationship'],
      '@skills' => $values['custom_menu_skills'],
    )
  );

  $setFitstName='Dmitry';
  variable_set('custom_menu_firstName',$setFitstName);

  $setLastName='Zrayev';
  variable_set('custom_menu_lastName',$setLastName);

  drupal_set_message($message);
}
