<?php

/**
 * Implements hook_custom_menu_menu().
 */
function second_menu_custom_menu_menu($route) {
  $subitems = [];
  if ($route == 'admin/menu_custom') {
    $subitems['next-first-alter'] = array(
      'title' => 'Contact',
      'access callback' => TRUE,
      'expanded' => TRUE,
      'page callback' => 'custom_menu_page_callback',
      'weight' => 4, );
  }
  return $subitems;
}

/**
 * Implements hook_custom_menu_menu_alter().
 */
function second_menu_custom_menu_menu_alter(&$subitems, $route) {
  if ($route == 'admin/menu_custom') {
    $subitems['help']['title'] = 'Site help';
  }
}

